# Generated by Django 5.2.16 on 2026-08-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscrição WhatsApp',
                'verbose_name_plural': 'Inscrições WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
    ]
