# Generated by Django 5.2.16 on 2026-08-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_inscricaowhatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoAlertaClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contato alerta clima',
                'verbose_name_plural': 'Contatos alerta clima',
                'ordering': ['nome', 'telefone'],
            },
        ),
    ]
