# Generated by Django 5.2.16 on 2026-08-13 04:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(default='Rural Pro Amazônia', max_length=120, verbose_name='Nome do site')),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, default='Manaus', max_length=80)),
                ('estado', models.CharField(blank=True, default='AM', max_length=2)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('pilar_1_titulo', models.CharField(default='Sustentabilidade', max_length=80)),
                ('pilar_1_texto', models.TextField(blank=True)),
                ('pilar_2_titulo', models.CharField(default='Inovação', max_length=80)),
                ('pilar_2_texto', models.TextField(blank=True)),
                ('pilar_3_titulo', models.CharField(default='Comunidade', max_length=80)),
                ('pilar_3_texto', models.TextField(blank=True)),
                ('texto_rodape', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configuração do site',
            },
        ),
        migrations.CreateModel(
            name='HistoriaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nossa história', max_length=200)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='historia/')),
            ],
            options={
                'verbose_name': 'História da empresa',
                'verbose_name_plural': 'História da empresa',
            },
        ),
        migrations.CreateModel(
            name='SlideHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('imagem_estatica', models.CharField(blank=True, help_text='Caminho relativo em static, ex: img/hero-1.jpg', max_length=120, verbose_name='Imagem estática (static/img)')),
                ('texto_botao', models.CharField(blank=True, default='Saiba mais', max_length=60)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slide do hero',
                'verbose_name_plural': 'Slides do hero',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
