# Generated by Django 5.2.16 on 2026-08-13 04:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('resumo', models.TextField(max_length=400)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='servicos/')),
                ('imagem_estatica', models.CharField(blank=True, max_length=120)),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
