# Generated by Django 5.2.16 on 2026-08-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='link',
            field=models.URLField(blank=True, help_text='Site ou página relacionada ao serviço.', max_length=300, verbose_name='Link externo'),
        ),
    ]
