# Generated by Django 5.2.16 on 2026-08-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servico_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='link',
            field=models.CharField(blank=True, help_text='Ex.: https://buscarural.com.br', max_length=300, verbose_name='Link externo'),
        ),
    ]
