# Generated by Django 5.2.17 on 2026-08-14 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('selo_verde_acre', 'Selo Verde Acre')], default='selo_verde_acre', max_length=40)),
                ('numero_car', models.CharField(db_index=True, max_length=120, verbose_name='Código CAR')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='buscarrural/selo_verde/')),
                ('atualizado_em_site', models.CharField(blank=True, max_length=40)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_buscarrural', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta BuscarRural',
                'verbose_name_plural': 'Histórico BuscarRural',
                'ordering': ['-criado_em'],
            },
        ),
    ]
