# Generated by Django 5.2.17 on 2026-08-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscarrural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultahistorico',
            name='parecer',
            field=models.TextField(blank=True, verbose_name='Parecer IA'),
        ),
    ]
