# Generated by Django 5.2.17 on 2026-08-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscarrural', '0002_consultahistorico_parecer'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultahistorico',
            name='alertas_criticos',
            field=models.TextField(blank=True, verbose_name='Alertas críticos IA'),
        ),
    ]
