# Generated by Django 5.2.17 on 2026-08-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscarrural', '0003_alertas_criticos'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultahistorico',
            name='imagem_terreno',
            field=models.ImageField(blank=True, null=True, upload_to='buscarrural/terreno/', verbose_name='Mapa do imóvel'),
        ),
        migrations.AddField(
            model_name='consultahistorico',
            name='parecer_diagnostico',
            field=models.JSONField(blank=True, default=dict, verbose_name='Diagnóstico estruturado IA'),
        ),
    ]
